# coding: utf-8

"""
    Resources and endpoints

    When I started SignWell in 2019, I saw there was a need for an alternative to the hard-to-use and expensive e-signature software already out there. Documents can be complicated enough, but getting a document signed shouldn't be complicated too.  At SignWell, we pride ourselves not only on the ease and affordability of our e-signature process but also on our personalized and industry-leading customer support — whether it's for individual use or larger team accounts, SignWell is here to help you feel comfortable and confident getting your documents signed.  The SignWell mission? Simplify how documents get signed for millions of people and businesses. We're excited to help you continue to move toward the future of paperless document signing.  Ruben Gamez Founder, SignWell

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sign_well_python_sdk.type.document_from_template_response_fields_item_item_recipient import DocumentFromTemplateResponseFieldsItemItemRecipient

class RequiredDocumentFromTemplateResponseFieldsItemItem(TypedDict):
    x: typing.Union[int, float]

    y: typing.Union[int, float]

    page: int

class OptionalDocumentFromTemplateResponseFieldsItemItem(TypedDict, total=False):
    recipient: DocumentFromTemplateResponseFieldsItemItemRecipient

    api_id: str

    date_format: str

    fixed_width: bool

    label: str

    lock_sign_date: bool

    required: bool

    type: str

    validation: str

    value: typing.Union[bool, date, datetime, dict, float, int, list, str, None]

class DocumentFromTemplateResponseFieldsItemItem(RequiredDocumentFromTemplateResponseFieldsItemItem, OptionalDocumentFromTemplateResponseFieldsItemItem):
    pass
