# coding: utf-8

"""
    Resources and endpoints

    When I started SignWell in 2019, I saw there was a need for an alternative to the hard-to-use and expensive e-signature software already out there. Documents can be complicated enough, but getting a document signed shouldn't be complicated too.  At SignWell, we pride ourselves not only on the ease and affordability of our e-signature process but also on our personalized and industry-leading customer support — whether it's for individual use or larger team accounts, SignWell is here to help you feel comfortable and confident getting your documents signed.  The SignWell mission? Simplify how documents get signed for millions of people and businesses. We're excited to help you continue to move toward the future of paperless document signing.  Ruben Gamez Founder, SignWell

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from sign_well_python_sdk.type.document_create_from_template422_response_errors_fields_file2_field1 import DocumentCreateFromTemplate422ResponseErrorsFieldsFile2Field1
from sign_well_python_sdk.type.document_create_from_template422_response_errors_fields_file2_field2 import DocumentCreateFromTemplate422ResponseErrorsFieldsFile2Field2
from sign_well_python_sdk.type.document_create_from_template422_response_errors_fields_file2_field3 import DocumentCreateFromTemplate422ResponseErrorsFieldsFile2Field3
from sign_well_python_sdk.type.document_create_from_template422_response_errors_fields_file2_field4 import DocumentCreateFromTemplate422ResponseErrorsFieldsFile2Field4

class RequiredDocumentCreateFromTemplate422ResponseErrorsFieldsFile2(TypedDict):
    pass

class OptionalDocumentCreateFromTemplate422ResponseErrorsFieldsFile2(TypedDict, total=False):
    field_1: DocumentCreateFromTemplate422ResponseErrorsFieldsFile2Field1

    field_2: DocumentCreateFromTemplate422ResponseErrorsFieldsFile2Field2

    field_3: DocumentCreateFromTemplate422ResponseErrorsFieldsFile2Field3

    field_4: DocumentCreateFromTemplate422ResponseErrorsFieldsFile2Field4

class DocumentCreateFromTemplate422ResponseErrorsFieldsFile2(RequiredDocumentCreateFromTemplate422ResponseErrorsFieldsFile2, OptionalDocumentCreateFromTemplate422ResponseErrorsFieldsFile2):
    pass
