# coding: utf-8

"""
    Resources and endpoints

    When I started SignWell in 2019, I saw there was a need for an alternative to the hard-to-use and expensive e-signature software already out there. Documents can be complicated enough, but getting a document signed shouldn't be complicated too.  At SignWell, we pride ourselves not only on the ease and affordability of our e-signature process but also on our personalized and industry-leading customer support — whether it's for individual use or larger team accounts, SignWell is here to help you feel comfortable and confident getting your documents signed.  The SignWell mission? Simplify how documents get signed for millions of people and businesses. We're excited to help you continue to move toward the future of paperless document signing.  Ruben Gamez Founder, SignWell

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from sign_well_python_sdk.pydantic.template_create_new422_response_errors_files_file1 import TemplateCreateNew422ResponseErrorsFilesFile1
from sign_well_python_sdk.pydantic.template_create_new422_response_errors_files_file2 import TemplateCreateNew422ResponseErrorsFilesFile2
from sign_well_python_sdk.pydantic.template_create_new422_response_errors_files_file3 import TemplateCreateNew422ResponseErrorsFilesFile3
from sign_well_python_sdk.pydantic.template_create_new422_response_errors_files_file4 import TemplateCreateNew422ResponseErrorsFilesFile4
from sign_well_python_sdk.pydantic.template_create_new422_response_errors_files_file5 import TemplateCreateNew422ResponseErrorsFilesFile5
from sign_well_python_sdk.pydantic.template_create_new422_response_errors_files_file6 import TemplateCreateNew422ResponseErrorsFilesFile6
from sign_well_python_sdk.pydantic.template_create_new422_response_errors_files_file7 import TemplateCreateNew422ResponseErrorsFilesFile7
from sign_well_python_sdk.pydantic.template_create_new422_response_errors_files_file8 import TemplateCreateNew422ResponseErrorsFilesFile8

class TemplateCreateNew422ResponseErrorsFiles(BaseModel):
    file_1: typing.Optional[TemplateCreateNew422ResponseErrorsFilesFile1] = Field(None, alias='file_1')

    file_2: typing.Optional[TemplateCreateNew422ResponseErrorsFilesFile2] = Field(None, alias='file_2')

    file_3: typing.Optional[TemplateCreateNew422ResponseErrorsFilesFile3] = Field(None, alias='file_3')

    file_4: typing.Optional[TemplateCreateNew422ResponseErrorsFilesFile4] = Field(None, alias='file_4')

    file_5: typing.Optional[TemplateCreateNew422ResponseErrorsFilesFile5] = Field(None, alias='file_5')

    file_6: typing.Optional[TemplateCreateNew422ResponseErrorsFilesFile6] = Field(None, alias='file_6')

    file_7: typing.Optional[TemplateCreateNew422ResponseErrorsFilesFile7] = Field(None, alias='file_7')

    file_8: typing.Optional[TemplateCreateNew422ResponseErrorsFilesFile8] = Field(None, alias='file_8')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
