# coding: utf-8

"""
    Resources and endpoints

    When I started SignWell in 2019, I saw there was a need for an alternative to the hard-to-use and expensive e-signature software already out there. Documents can be complicated enough, but getting a document signed shouldn't be complicated too.  At SignWell, we pride ourselves not only on the ease and affordability of our e-signature process but also on our personalized and industry-leading customer support — whether it's for individual use or larger team accounts, SignWell is here to help you feel comfortable and confident getting your documents signed.  The SignWell mission? Simplify how documents get signed for millions of people and businesses. We're excited to help you continue to move toward the future of paperless document signing.  Ruben Gamez Founder, SignWell

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from sign_well_python_sdk.pydantic.expires_in_map import ExpiresInMap

class UpdateDocumentAndSendRequest(BaseModel):
    # Set to `true` to enable Test Mode. Documents created with Test Mode do not count towards API billing and are not legally binding. Defaults to `false`
    test_mode: typing.Optional[bool] = Field(None, alias='test_mode')

    # The name of the document.
    name: typing.Optional[str] = Field(None, alias='name')

    # Email subject for the signature request that recipients will see. Defaults to the default system subject or a template subject (if the document is created from a template).
    subject: typing.Optional[str] = Field(None, alias='subject')

    # Email message for the signature request that recipients will see. Defaults to the default system message or a template message (if the document is created from a template).
    message: typing.Optional[str] = Field(None, alias='message')

    expires_in: typing.Optional[ExpiresInMap] = Field(None, alias='expires_in')

    # Whether to send signing reminders to recipients. Reminders are sent on day 3, day 6, and day 10 if set to `true`. Defaults to `true`.
    reminders: typing.Optional[bool] = Field(None, alias='reminders')

    # When set to `true` recipients will sign one at a time in the order of the `recipients` collection of this request.
    apply_signing_order: typing.Optional[bool] = Field(None, alias='apply_signing_order')

    # Unique identifier for API Application settings to use. API Applications are optional and mainly used when isolating OAuth apps or for more control over embedded API settings
    api_application_id: typing.Optional[str] = Field(None, alias='api_application_id')

    # When set to `true` it enables embedded signing in your website/web application. Embedded functionality works with an iFrame and email authentication is disabled. :embedded_signinig defaults to `false`.
    embedded_signing: typing.Optional[bool] = Field(None, alias='embedded_signing')

    # On embedding signing, document owners (and CC'd contacts) do not get a notification email when documents have been completed. Setting this param to `true` will send out those final completed notifications. Default is `false`
    embedded_signing_notifications: typing.Optional[bool] = Field(None, alias='embedded_signing_notifications')

    # Sets the custom requester name for the document. When set, this is the name used for all email communications, signing notifications, and in the audit file.
    custom_requester_name: typing.Optional[str] = Field(None, alias='custom_requester_name')

    # Sets the custom requester email for the document. When set, this is the email used for all email communications, signing notifications, and in the audit file.
    custom_requester_email: typing.Optional[str] = Field(None, alias='custom_requester_email')

    # A URL that recipients are redirected to after successfully signing a document.
    redirect_url: typing.Optional[str] = Field(None, alias='redirect_url')

    # Whether to allow recipients the option to decline signing a document. If multiple signers are involved in a document, any single recipient can cancel the entire document signing process by declining to sign.
    allow_decline: typing.Optional[bool] = Field(None, alias='allow_decline')

    # In some cases a signer is not the right person to sign and may need to reassign their signing responsibilities to another person. This feature allows them to reassign the document to someone else.
    allow_reassign: typing.Optional[bool] = Field(None, alias='allow_reassign')

    # A URL that recipients are redirected to if the document is declined.
    decline_redirect_url: typing.Optional[str] = Field(None, alias='decline_redirect_url')

    # Optional key-value data that can be associated with the document. If set, will be available every time the document data is returned.
    metadata: typing.Optional[typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]] = Field(None, alias='metadata')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
