# coding: utf-8

"""
    Resources and endpoints

    When I started SignWell in 2019, I saw there was a need for an alternative to the hard-to-use and expensive e-signature software already out there. Documents can be complicated enough, but getting a document signed shouldn't be complicated too.  At SignWell, we pride ourselves not only on the ease and affordability of our e-signature process but also on our personalized and industry-leading customer support — whether it's for individual use or larger team accounts, SignWell is here to help you feel comfortable and confident getting your documents signed.  The SignWell mission? Simplify how documents get signed for millions of people and businesses. We're excited to help you continue to move toward the future of paperless document signing.  Ruben Gamez Founder, SignWell

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from sign_well_python_sdk import schemas  # noqa: F401


class DocumentCreateFromTemplate422ResponseErrors(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def name() -> typing.Type['DocumentCreateFromTemplate422ResponseErrorsName']:
                return DocumentCreateFromTemplate422ResponseErrorsName
            template_id_or_ids = schemas.StrSchema
        
            @staticmethod
            def custom_requester_email() -> typing.Type['DocumentCreateFromTemplate422ResponseErrorsCustomRequesterEmail']:
                return DocumentCreateFromTemplate422ResponseErrorsCustomRequesterEmail
        
            @staticmethod
            def custom_requester_name() -> typing.Type['DocumentCreateFromTemplate422ResponseErrorsCustomRequesterName']:
                return DocumentCreateFromTemplate422ResponseErrorsCustomRequesterName
        
            @staticmethod
            def decline_redirect_url() -> typing.Type['DocumentCreateFromTemplate422ResponseErrorsDeclineRedirectUrl']:
                return DocumentCreateFromTemplate422ResponseErrorsDeclineRedirectUrl
        
            @staticmethod
            def redirect_url() -> typing.Type['DocumentCreateFromTemplate422ResponseErrorsRedirectUrl']:
                return DocumentCreateFromTemplate422ResponseErrorsRedirectUrl
        
            @staticmethod
            def expires_in() -> typing.Type['DocumentCreateFromTemplate422ResponseErrorsExpiresIn']:
                return DocumentCreateFromTemplate422ResponseErrorsExpiresIn
        
            @staticmethod
            def metadata() -> typing.Type['DocumentCreateFromTemplate422ResponseErrorsMetadata']:
                return DocumentCreateFromTemplate422ResponseErrorsMetadata
        
            @staticmethod
            def api_application_id() -> typing.Type['DocumentCreateFromTemplate422ResponseErrorsApiApplicationId']:
                return DocumentCreateFromTemplate422ResponseErrorsApiApplicationId
        
            @staticmethod
            def subject() -> typing.Type['DocumentCreateFromTemplate422ResponseErrorsSubject']:
                return DocumentCreateFromTemplate422ResponseErrorsSubject
        
            @staticmethod
            def message() -> typing.Type['DocumentCreateFromTemplate422ResponseErrorsMessage']:
                return DocumentCreateFromTemplate422ResponseErrorsMessage
        
            @staticmethod
            def recipients() -> typing.Type['DocumentCreateFromTemplate422ResponseErrorsRecipients']:
                return DocumentCreateFromTemplate422ResponseErrorsRecipients
        
            @staticmethod
            def copied_contacts() -> typing.Type['DocumentCreateFromTemplate422ResponseErrorsCopiedContacts']:
                return DocumentCreateFromTemplate422ResponseErrorsCopiedContacts
        
            @staticmethod
            def attachment_requests() -> typing.Type['DocumentCreateFromTemplate422ResponseErrorsAttachmentRequests']:
                return DocumentCreateFromTemplate422ResponseErrorsAttachmentRequests
        
            @staticmethod
            def fields() -> typing.Type['DocumentCreateFromTemplate422ResponseErrorsFields']:
                return DocumentCreateFromTemplate422ResponseErrorsFields
        
            @staticmethod
            def files() -> typing.Type['DocumentCreateFromTemplate422ResponseErrorsFiles']:
                return DocumentCreateFromTemplate422ResponseErrorsFiles
            __annotations__ = {
                "name": name,
                "template_id_or_ids": template_id_or_ids,
                "custom_requester_email": custom_requester_email,
                "custom_requester_name": custom_requester_name,
                "decline_redirect_url": decline_redirect_url,
                "redirect_url": redirect_url,
                "expires_in": expires_in,
                "metadata": metadata,
                "api_application_id": api_application_id,
                "subject": subject,
                "message": message,
                "recipients": recipients,
                "copied_contacts": copied_contacts,
                "attachment_requests": attachment_requests,
                "fields": fields,
                "files": files,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> 'DocumentCreateFromTemplate422ResponseErrorsName': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["template_id_or_ids"]) -> MetaOapg.properties.template_id_or_ids: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["custom_requester_email"]) -> 'DocumentCreateFromTemplate422ResponseErrorsCustomRequesterEmail': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["custom_requester_name"]) -> 'DocumentCreateFromTemplate422ResponseErrorsCustomRequesterName': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["decline_redirect_url"]) -> 'DocumentCreateFromTemplate422ResponseErrorsDeclineRedirectUrl': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["redirect_url"]) -> 'DocumentCreateFromTemplate422ResponseErrorsRedirectUrl': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["expires_in"]) -> 'DocumentCreateFromTemplate422ResponseErrorsExpiresIn': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["metadata"]) -> 'DocumentCreateFromTemplate422ResponseErrorsMetadata': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["api_application_id"]) -> 'DocumentCreateFromTemplate422ResponseErrorsApiApplicationId': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["subject"]) -> 'DocumentCreateFromTemplate422ResponseErrorsSubject': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["message"]) -> 'DocumentCreateFromTemplate422ResponseErrorsMessage': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["recipients"]) -> 'DocumentCreateFromTemplate422ResponseErrorsRecipients': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["copied_contacts"]) -> 'DocumentCreateFromTemplate422ResponseErrorsCopiedContacts': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["attachment_requests"]) -> 'DocumentCreateFromTemplate422ResponseErrorsAttachmentRequests': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["fields"]) -> 'DocumentCreateFromTemplate422ResponseErrorsFields': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["files"]) -> 'DocumentCreateFromTemplate422ResponseErrorsFiles': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["name", "template_id_or_ids", "custom_requester_email", "custom_requester_name", "decline_redirect_url", "redirect_url", "expires_in", "metadata", "api_application_id", "subject", "message", "recipients", "copied_contacts", "attachment_requests", "fields", "files", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> typing.Union['DocumentCreateFromTemplate422ResponseErrorsName', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["template_id_or_ids"]) -> typing.Union[MetaOapg.properties.template_id_or_ids, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["custom_requester_email"]) -> typing.Union['DocumentCreateFromTemplate422ResponseErrorsCustomRequesterEmail', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["custom_requester_name"]) -> typing.Union['DocumentCreateFromTemplate422ResponseErrorsCustomRequesterName', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["decline_redirect_url"]) -> typing.Union['DocumentCreateFromTemplate422ResponseErrorsDeclineRedirectUrl', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["redirect_url"]) -> typing.Union['DocumentCreateFromTemplate422ResponseErrorsRedirectUrl', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["expires_in"]) -> typing.Union['DocumentCreateFromTemplate422ResponseErrorsExpiresIn', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["metadata"]) -> typing.Union['DocumentCreateFromTemplate422ResponseErrorsMetadata', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["api_application_id"]) -> typing.Union['DocumentCreateFromTemplate422ResponseErrorsApiApplicationId', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["subject"]) -> typing.Union['DocumentCreateFromTemplate422ResponseErrorsSubject', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["message"]) -> typing.Union['DocumentCreateFromTemplate422ResponseErrorsMessage', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["recipients"]) -> typing.Union['DocumentCreateFromTemplate422ResponseErrorsRecipients', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["copied_contacts"]) -> typing.Union['DocumentCreateFromTemplate422ResponseErrorsCopiedContacts', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["attachment_requests"]) -> typing.Union['DocumentCreateFromTemplate422ResponseErrorsAttachmentRequests', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["fields"]) -> typing.Union['DocumentCreateFromTemplate422ResponseErrorsFields', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["files"]) -> typing.Union['DocumentCreateFromTemplate422ResponseErrorsFiles', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["name", "template_id_or_ids", "custom_requester_email", "custom_requester_name", "decline_redirect_url", "redirect_url", "expires_in", "metadata", "api_application_id", "subject", "message", "recipients", "copied_contacts", "attachment_requests", "fields", "files", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        name: typing.Union['DocumentCreateFromTemplate422ResponseErrorsName', schemas.Unset] = schemas.unset,
        template_id_or_ids: typing.Union[MetaOapg.properties.template_id_or_ids, str, schemas.Unset] = schemas.unset,
        custom_requester_email: typing.Union['DocumentCreateFromTemplate422ResponseErrorsCustomRequesterEmail', schemas.Unset] = schemas.unset,
        custom_requester_name: typing.Union['DocumentCreateFromTemplate422ResponseErrorsCustomRequesterName', schemas.Unset] = schemas.unset,
        decline_redirect_url: typing.Union['DocumentCreateFromTemplate422ResponseErrorsDeclineRedirectUrl', schemas.Unset] = schemas.unset,
        redirect_url: typing.Union['DocumentCreateFromTemplate422ResponseErrorsRedirectUrl', schemas.Unset] = schemas.unset,
        expires_in: typing.Union['DocumentCreateFromTemplate422ResponseErrorsExpiresIn', schemas.Unset] = schemas.unset,
        metadata: typing.Union['DocumentCreateFromTemplate422ResponseErrorsMetadata', schemas.Unset] = schemas.unset,
        api_application_id: typing.Union['DocumentCreateFromTemplate422ResponseErrorsApiApplicationId', schemas.Unset] = schemas.unset,
        subject: typing.Union['DocumentCreateFromTemplate422ResponseErrorsSubject', schemas.Unset] = schemas.unset,
        message: typing.Union['DocumentCreateFromTemplate422ResponseErrorsMessage', schemas.Unset] = schemas.unset,
        recipients: typing.Union['DocumentCreateFromTemplate422ResponseErrorsRecipients', schemas.Unset] = schemas.unset,
        copied_contacts: typing.Union['DocumentCreateFromTemplate422ResponseErrorsCopiedContacts', schemas.Unset] = schemas.unset,
        attachment_requests: typing.Union['DocumentCreateFromTemplate422ResponseErrorsAttachmentRequests', schemas.Unset] = schemas.unset,
        fields: typing.Union['DocumentCreateFromTemplate422ResponseErrorsFields', schemas.Unset] = schemas.unset,
        files: typing.Union['DocumentCreateFromTemplate422ResponseErrorsFiles', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'DocumentCreateFromTemplate422ResponseErrors':
        return super().__new__(
            cls,
            *args,
            name=name,
            template_id_or_ids=template_id_or_ids,
            custom_requester_email=custom_requester_email,
            custom_requester_name=custom_requester_name,
            decline_redirect_url=decline_redirect_url,
            redirect_url=redirect_url,
            expires_in=expires_in,
            metadata=metadata,
            api_application_id=api_application_id,
            subject=subject,
            message=message,
            recipients=recipients,
            copied_contacts=copied_contacts,
            attachment_requests=attachment_requests,
            fields=fields,
            files=files,
            _configuration=_configuration,
            **kwargs,
        )

from sign_well_python_sdk.model.document_create_from_template422_response_errors_api_application_id import DocumentCreateFromTemplate422ResponseErrorsApiApplicationId
from sign_well_python_sdk.model.document_create_from_template422_response_errors_attachment_requests import DocumentCreateFromTemplate422ResponseErrorsAttachmentRequests
from sign_well_python_sdk.model.document_create_from_template422_response_errors_copied_contacts import DocumentCreateFromTemplate422ResponseErrorsCopiedContacts
from sign_well_python_sdk.model.document_create_from_template422_response_errors_custom_requester_email import DocumentCreateFromTemplate422ResponseErrorsCustomRequesterEmail
from sign_well_python_sdk.model.document_create_from_template422_response_errors_custom_requester_name import DocumentCreateFromTemplate422ResponseErrorsCustomRequesterName
from sign_well_python_sdk.model.document_create_from_template422_response_errors_decline_redirect_url import DocumentCreateFromTemplate422ResponseErrorsDeclineRedirectUrl
from sign_well_python_sdk.model.document_create_from_template422_response_errors_expires_in import DocumentCreateFromTemplate422ResponseErrorsExpiresIn
from sign_well_python_sdk.model.document_create_from_template422_response_errors_fields import DocumentCreateFromTemplate422ResponseErrorsFields
from sign_well_python_sdk.model.document_create_from_template422_response_errors_files import DocumentCreateFromTemplate422ResponseErrorsFiles
from sign_well_python_sdk.model.document_create_from_template422_response_errors_message import DocumentCreateFromTemplate422ResponseErrorsMessage
from sign_well_python_sdk.model.document_create_from_template422_response_errors_metadata import DocumentCreateFromTemplate422ResponseErrorsMetadata
from sign_well_python_sdk.model.document_create_from_template422_response_errors_name import DocumentCreateFromTemplate422ResponseErrorsName
from sign_well_python_sdk.model.document_create_from_template422_response_errors_recipients import DocumentCreateFromTemplate422ResponseErrorsRecipients
from sign_well_python_sdk.model.document_create_from_template422_response_errors_redirect_url import DocumentCreateFromTemplate422ResponseErrorsRedirectUrl
from sign_well_python_sdk.model.document_create_from_template422_response_errors_subject import DocumentCreateFromTemplate422ResponseErrorsSubject
