# coding: utf-8

"""
    Resources and endpoints

    When I started SignWell in 2019, I saw there was a need for an alternative to the hard-to-use and expensive e-signature software already out there. Documents can be complicated enough, but getting a document signed shouldn't be complicated too.  At SignWell, we pride ourselves not only on the ease and affordability of our e-signature process but also on our personalized and industry-leading customer support — whether it's for individual use or larger team accounts, SignWell is here to help you feel comfortable and confident getting your documents signed.  The SignWell mission? Simplify how documents get signed for millions of people and businesses. We're excited to help you continue to move toward the future of paperless document signing.  Ruben Gamez Founder, SignWell

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from sign_well_python_sdk import schemas  # noqa: F401


class DocumentCreateNewDocument422ResponseErrorsFields(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
            duplicated_api_ids = schemas.StrSchema
            invalid_ids = schemas.StrSchema
        
            @staticmethod
            def file_1() -> typing.Type['DocumentCreateNewDocument422ResponseErrorsFieldsFile1']:
                return DocumentCreateNewDocument422ResponseErrorsFieldsFile1
        
            @staticmethod
            def file_2() -> typing.Type['DocumentCreateNewDocument422ResponseErrorsFieldsFile2']:
                return DocumentCreateNewDocument422ResponseErrorsFieldsFile2
            __annotations__ = {
                "duplicated_api_ids": duplicated_api_ids,
                "invalid_ids": invalid_ids,
                "file_1": file_1,
                "file_2": file_2,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["duplicated_api_ids"]) -> MetaOapg.properties.duplicated_api_ids: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["invalid_ids"]) -> MetaOapg.properties.invalid_ids: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["file_1"]) -> 'DocumentCreateNewDocument422ResponseErrorsFieldsFile1': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["file_2"]) -> 'DocumentCreateNewDocument422ResponseErrorsFieldsFile2': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["duplicated_api_ids", "invalid_ids", "file_1", "file_2", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["duplicated_api_ids"]) -> typing.Union[MetaOapg.properties.duplicated_api_ids, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["invalid_ids"]) -> typing.Union[MetaOapg.properties.invalid_ids, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["file_1"]) -> typing.Union['DocumentCreateNewDocument422ResponseErrorsFieldsFile1', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["file_2"]) -> typing.Union['DocumentCreateNewDocument422ResponseErrorsFieldsFile2', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["duplicated_api_ids", "invalid_ids", "file_1", "file_2", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        duplicated_api_ids: typing.Union[MetaOapg.properties.duplicated_api_ids, str, schemas.Unset] = schemas.unset,
        invalid_ids: typing.Union[MetaOapg.properties.invalid_ids, str, schemas.Unset] = schemas.unset,
        file_1: typing.Union['DocumentCreateNewDocument422ResponseErrorsFieldsFile1', schemas.Unset] = schemas.unset,
        file_2: typing.Union['DocumentCreateNewDocument422ResponseErrorsFieldsFile2', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'DocumentCreateNewDocument422ResponseErrorsFields':
        return super().__new__(
            cls,
            *args,
            duplicated_api_ids=duplicated_api_ids,
            invalid_ids=invalid_ids,
            file_1=file_1,
            file_2=file_2,
            _configuration=_configuration,
            **kwargs,
        )

from sign_well_python_sdk.model.document_create_new_document422_response_errors_fields_file1 import DocumentCreateNewDocument422ResponseErrorsFieldsFile1
from sign_well_python_sdk.model.document_create_new_document422_response_errors_fields_file2 import DocumentCreateNewDocument422ResponseErrorsFieldsFile2
