# coding: utf-8

"""
    Resources and endpoints

    When I started SignWell in 2019, I saw there was a need for an alternative to the hard-to-use and expensive e-signature software already out there. Documents can be complicated enough, but getting a document signed shouldn't be complicated too.  At SignWell, we pride ourselves not only on the ease and affordability of our e-signature process but also on our personalized and industry-leading customer support — whether it's for individual use or larger team accounts, SignWell is here to help you feel comfortable and confident getting your documents signed.  The SignWell mission? Simplify how documents get signed for millions of people and businesses. We're excited to help you continue to move toward the future of paperless document signing.  Ruben Gamez Founder, SignWell

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from sign_well_python_sdk import schemas  # noqa: F401


class DocumentCreateFromTemplate422ResponseErrorsCopiedContactsCopiedContact1(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def name() -> typing.Type['DocumentCreateFromTemplate422ResponseErrorsCopiedContactsCopiedContact1Name']:
                return DocumentCreateFromTemplate422ResponseErrorsCopiedContactsCopiedContact1Name
        
            @staticmethod
            def email() -> typing.Type['DocumentCreateFromTemplate422ResponseErrorsCopiedContactsCopiedContact1Email']:
                return DocumentCreateFromTemplate422ResponseErrorsCopiedContactsCopiedContact1Email
            __annotations__ = {
                "name": name,
                "email": email,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["name"]) -> 'DocumentCreateFromTemplate422ResponseErrorsCopiedContactsCopiedContact1Name': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["email"]) -> 'DocumentCreateFromTemplate422ResponseErrorsCopiedContactsCopiedContact1Email': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["name", "email", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["name"]) -> typing.Union['DocumentCreateFromTemplate422ResponseErrorsCopiedContactsCopiedContact1Name', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["email"]) -> typing.Union['DocumentCreateFromTemplate422ResponseErrorsCopiedContactsCopiedContact1Email', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["name", "email", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        name: typing.Union['DocumentCreateFromTemplate422ResponseErrorsCopiedContactsCopiedContact1Name', schemas.Unset] = schemas.unset,
        email: typing.Union['DocumentCreateFromTemplate422ResponseErrorsCopiedContactsCopiedContact1Email', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'DocumentCreateFromTemplate422ResponseErrorsCopiedContactsCopiedContact1':
        return super().__new__(
            cls,
            *args,
            name=name,
            email=email,
            _configuration=_configuration,
            **kwargs,
        )

from sign_well_python_sdk.model.document_create_from_template422_response_errors_copied_contacts_copied_contact1_email import DocumentCreateFromTemplate422ResponseErrorsCopiedContactsCopiedContact1Email
from sign_well_python_sdk.model.document_create_from_template422_response_errors_copied_contacts_copied_contact1_name import DocumentCreateFromTemplate422ResponseErrorsCopiedContactsCopiedContact1Name
