# coding: utf-8

"""
    Resources and endpoints

    When I started SignWell in 2019, I saw there was a need for an alternative to the hard-to-use and expensive e-signature software already out there. Documents can be complicated enough, but getting a document signed shouldn't be complicated too.  At SignWell, we pride ourselves not only on the ease and affordability of our e-signature process but also on our personalized and industry-leading customer support — whether it's for individual use or larger team accounts, SignWell is here to help you feel comfortable and confident getting your documents signed.  The SignWell mission? Simplify how documents get signed for millions of people and businesses. We're excited to help you continue to move toward the future of paperless document signing.  Ruben Gamez Founder, SignWell

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

import unittest

import sign_well_python_sdk
from sign_well_python_sdk.model.template_update_existing_template_response_metadata import TemplateUpdateExistingTemplateResponseMetadata
from sign_well_python_sdk import configuration


class TestTemplateUpdateExistingTemplateResponseMetadata(unittest.TestCase):
    """TemplateUpdateExistingTemplateResponseMetadata unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
