# coding: utf-8
"""
    Resources and endpoints

    When I started SignWell in 2019, I saw there was a need for an alternative to the hard-to-use and expensive e-signature software already out there. Documents can be complicated enough, but getting a document signed shouldn't be complicated too.  At SignWell, we pride ourselves not only on the ease and affordability of our e-signature process but also on our personalized and industry-leading customer support — whether it's for individual use or larger team accounts, SignWell is here to help you feel comfortable and confident getting your documents signed.  The SignWell mission? Simplify how documents get signed for millions of people and businesses. We're excited to help you continue to move toward the future of paperless document signing.  Ruben Gamez Founder, SignWell

    The version of the OpenAPI document: 1
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from sign_well_python_sdk.client_custom import ClientCustom
from sign_well_python_sdk.configuration import Configuration
from sign_well_python_sdk.api_client import ApiClient
from sign_well_python_sdk.type_util import copy_signature
from sign_well_python_sdk.apis.tags.api_application_api import APIApplicationApi
from sign_well_python_sdk.apis.tags.bulk_send_api import BulkSendApi
from sign_well_python_sdk.apis.tags.document_api import DocumentApi
from sign_well_python_sdk.apis.tags.me_api import MeApi
from sign_well_python_sdk.apis.tags.template_api import TemplateApi
from sign_well_python_sdk.apis.tags.webhooks_api import WebhooksApi



class SignWell(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.api_application: APIApplicationApi = APIApplicationApi(api_client)
        self.bulk_send: BulkSendApi = BulkSendApi(api_client)
        self.document: DocumentApi = DocumentApi(api_client)
        self.me: MeApi = MeApi(api_client)
        self.template: TemplateApi = TemplateApi(api_client)
        self.webhooks: WebhooksApi = WebhooksApi(api_client)
